#!/usr/bin/env python
# train_SST_RAD.py
#
# RAD-based SST reconstruction training script.
# Based on train_RAD.py, adapted for multi-channel SST input with:
#   - 3-channel input: [noisy_SST, ERA5, LandMask]
#   - 1-channel output: SST
#   - Geo-Temporal class conditioning
#   - ERA5 dropout (10% probability)
#   - Curriculum mask annealing (3-stage)
#   - Loss restricted to: Perlin-masked ∩ ocean ∩ QL=5 pixels
#   - v-prediction + Min-SNR loss
#   - EMA model
#   - DDIM inference for validation
#   - Validation set month filtering (e.g. 2023 Jan-Jun)
#   - Rich training logging + visualization

import warnings
warnings.filterwarnings(action="ignore")

import argparse
import logging
import math
import os
import random
import shutil
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")  # 非交互后端，服务器环境安全
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F
import torch.utils.checkpoint
from accelerate import Accelerator
from accelerate.logging import get_logger
from accelerate.utils import ProjectConfiguration, set_seed
from tqdm.auto import tqdm

import diffusers
from diffusers.schedulers.scheduling_localddpm import LocalDDPMScheduler
from diffusers.schedulers.scheduling_localddim import LocalDDIMScheduler
from diffusers.optimization import get_scheduler
from diffusers.training_utils import EMAModel, compute_snr
from diffusers.utils import check_min_version
from diffusers.utils.noise_gen_sst import generate_perlin_noise_2d  # 修复版
from diffusers.utils.set_random_steps import set_random_steps

from torch.utils.data import DataLoader

# 本项目自定义模块
from sst_dataset import (
    SSTDataset,
    FixedValDataset,
    MmapSSTDataset,
    MaskCurriculumScheduler,
    GeoTemporalEmbedding,
    compute_norm_stats,
    load_norm_stats,
)
from patch_unet_for_sst import build_sst_unet


check_min_version("0.28.0.dev0")
logger = get_logger(__name__, log_level="INFO")


# ============================================================
# 参数解析
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(description="RAD-based SST reconstruction training")

    # 数据
    parser.add_argument("--data_root", type=str, required=True,
                        help="Root directory of SST data (contains year subdirs)")
    parser.add_argument("--train_years", type=int, nargs="+", required=True,
                        help="Years to use for training, e.g. 2019 2020 2021 2022")
    parser.add_argument("--val_years",   type=int, nargs="+", required=True,
                        help="Years to use for validation, e.g. 2023")
    parser.add_argument("--val_months",  type=int, nargs="+", default=None,
                        help="Months to use for validation, e.g. 1 2 3 4 5 6 for Jan-Jun. "
                             "None = use all months of val_years.")
    parser.add_argument("--norm_stats_path", type=str, default="norm_stats.json",
                        help="Path to save/load normalization statistics")
    parser.add_argument("--max_train_samples", type=int, default=None,
                        help="Subsample training set to this many patches (None = use all). "
                             "Useful for smoke tests, e.g. --max_train_samples 200")
    parser.add_argument("--max_val_samples", type=int, default=None,
                        help="Subsample validation set to this many patches (None = use all). "
                             "Useful for smoke tests, e.g. --max_val_samples 100")
    parser.add_argument("--val_pt_path", type=str, default=None,
                        help="Path to fixed val set .pt file generated by prepare_val_set.py. "
                             "If provided, uses FixedValDataset instead of SSTDataset for validation, "
                             "which avoids LRU cache pressure. Recommended for cache mode training.")
    parser.add_argument("--train_mmap_index", type=str, default=None,
                        help="Path to train_index.json generated by build_mmap_dataset.py. "
                             "If provided, uses MmapSSTDataset for training: OS-level memory mapping "
                             "keeps physical RAM usage near zero regardless of dataset size, "
                             "enabling shuffle without OOM. Requires local SSD for best performance.")

    # 模型
    parser.add_argument("--block_out_channels", type=int, nargs="+",
                        default=[128, 256, 256, 256])
    parser.add_argument("--layers_per_block", type=int, default=2)
    parser.add_argument("--geo_emb_dim", type=int, default=256,
                        help="Gaussian Fourier geo embedding dimension (out_dim = 2 * num_fourier_features)")
    parser.add_argument("--geo_fourier_features", type=int, default=128)
    parser.add_argument("--geo_sigma", type=float, default=1.0,
                        help="Scale of Gaussian projection matrix for geo embedding")

    # 扩散
    parser.add_argument("--ddpm_num_steps",      type=int, default=2000)
    parser.add_argument("--ddpm_mask_num_steps",  type=int, default=1000)
    parser.add_argument("--ddpm_num_inference_steps", type=int, default=50,
                        help="DDIM inference steps for validation (default: 50)")
    parser.add_argument("--prediction_type",     type=str, default="v_prediction",
                        choices=["epsilon", "v_prediction"])
    parser.add_argument("--snr_gamma",           type=float, default=5.0,
                        help="Min-SNR gamma (set None to disable)")

    # 课程学习
    parser.add_argument("--curriculum_warmup_ratio", type=float, default=0.15)
    parser.add_argument("--curriculum_anneal_ratio",  type=float, default=0.55)
    parser.add_argument("--mask_min_rate",  type=float, default=0.10)
    parser.add_argument("--mask_max_rate",  type=float, default=0.75)
    parser.add_argument("--perlin_high_sig", type=float, default=15.0)
    parser.add_argument("--perlin_low_sig",  type=float, default=2.0)

    # ERA5 dropout
    parser.add_argument("--era5_dropout_prob", type=float, default=0.1,
                        help="Probability of zeroing ERA5 channel (classifier-free guidance style)")

    # 训练超参
    parser.add_argument("--output_dir",    type=str, default="sst_rad_output")
    parser.add_argument("--seed",          type=int, default=42)
    parser.add_argument("--resolution",    type=int, default=256)
    parser.add_argument("--train_batch_size", type=int, default=16)
    parser.add_argument("--num_train_epochs", type=int, default=200)
    parser.add_argument("--max_train_steps",  type=int, default=None)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--gradient_checkpointing", action="store_true")
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--lr_scheduler",  type=str, default="cosine")
    parser.add_argument("--lr_warmup_steps", type=int, default=2000)
    parser.add_argument("--adam_beta1",    type=float, default=0.9)
    parser.add_argument("--adam_beta2",    type=float, default=0.999)
    parser.add_argument("--adam_weight_decay", type=float, default=1e-2)
    parser.add_argument("--adam_epsilon",  type=float, default=1e-8)
    parser.add_argument("--max_grad_norm", type=float, default=1.0)
    parser.add_argument("--noise_offset",  type=float, default=0.0)
    parser.add_argument("--dataloader_num_workers", type=int, default=4)
    parser.add_argument("--log_every_n_steps", type=int, default=100,
                        help="Log training metrics every N steps")

    # EMA
    parser.add_argument("--use_ema",       action="store_true", default=True,
                        help="Use EMA model (default: True). Disable with --no_use_ema.")
    parser.add_argument("--no_use_ema",    dest="use_ema", action="store_false")
    parser.add_argument("--ema_inv_gamma", type=float, default=1.0)
    parser.add_argument("--ema_power",     type=float, default=0.75)
    parser.add_argument("--ema_max_decay", type=float, default=0.9999)

    # 日志与检查点
    parser.add_argument("--checkpointing_steps", type=int, default=5000)
    parser.add_argument("--checkpoints_total_limit", type=int, default=3)
    parser.add_argument("--resume_from_checkpoint", type=str, default=None)
    parser.add_argument("--logging_dir",   type=str, default="logs")
    parser.add_argument("--report_to",     type=str, default="tensorboard")
    parser.add_argument("--random_steps",  action="store_true")
    parser.add_argument("--val_every_n_steps", type=int, default=5000,
                        help="Run validation every N steps (default: 5000, aligned with checkpointing_steps)")
    parser.add_argument("--vis_num_samples", type=int, default=4,
                        help="Number of samples to visualize per validation (default: 4)")

    # 内存优化
    parser.add_argument("--enable_xformers_memory_efficient_attention", action="store_true")
    parser.add_argument("--allow_tf32",    action="store_true")
    parser.add_argument("--mixed_precision", type=str, default="bf16",
                        choices=["no", "fp16", "bf16"])

    args = parser.parse_args()
    return args


# ============================================================
# 主训练函数
# ============================================================

def main():
    args = parse_args()

    # ---- Accelerator ----
    logging_dir = os.path.join(args.output_dir, args.logging_dir)
    accelerator_project_config = ProjectConfiguration(
        project_dir=args.output_dir, logging_dir=logging_dir
    )
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.report_to,
        project_config=accelerator_project_config,
    )

    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )
    logger.info(accelerator.state, main_process_only=False)
    if accelerator.is_local_main_process:
        diffusers.utils.logging.set_verbosity_info()
    else:
        diffusers.utils.logging.set_verbosity_error()

    if args.seed is not None:
        set_seed(args.seed)

    if accelerator.is_main_process:
        os.makedirs(args.output_dir, exist_ok=True)
        os.makedirs(os.path.join(args.output_dir, "vis"), exist_ok=True)
        os.makedirs(logging_dir, exist_ok=True)

    if args.allow_tf32:
        torch.backends.cuda.matmul.allow_tf32 = True

    # ---- 归一化统计量 ----
    # 优先级：
    #   1. norm_stats_path 文件存在 → 直接读取（mmap 模式或已有 json 时走此路径）
    #   2. data_root 下有符合 YYYY_MM.pt 格式的文件 → 从第一个文件读 norm_params
    #   3. 两者都没有 → 从 NetCDF 原始数据计算并保存
    from glob import glob as _glob
    import re as _re

    # 只扫描 YYYY_MM.pt 格式的文件，避免 val_fixed_*.pt 等其他文件干扰
    _pt_files = [
        p for p in sorted(_glob(os.path.join(args.data_root, "*.pt")))
        if _re.match(r"^\d{4}_\d{2}\.pt$", os.path.basename(p))
    ]
    _cache_mode = len(_pt_files) > 0

    if os.path.exists(args.norm_stats_path):
        # 路径1：norm_stats_path 已存在，直接读取（最优先）
        norm_stats = load_norm_stats(args.norm_stats_path)
        logger.info(f"[NormStats] Loaded from {args.norm_stats_path}: {norm_stats}")
    elif _cache_mode:
        # 路径2：从第一个 YYYY_MM.pt 文件读取内嵌的 norm_params
        try:
            _sample_pt = torch.load(_pt_files[0], map_location="cpu", weights_only=True)
        except Exception:
            _sample_pt = torch.load(_pt_files[0], map_location="cpu", weights_only=False)
        norm_stats = _sample_pt["norm_params"]
        logger.info(f"[NormStats] Loaded from .pt file {os.path.basename(_pt_files[0])}: {norm_stats}")
    else:
        # 路径3：从 NetCDF 原始数据计算
        if accelerator.is_main_process:
            logger.info("Computing normalization statistics from training data...")
            norm_stats = compute_norm_stats(
                args.data_root, args.train_years,
                num_samples=5000,
                save_path=args.norm_stats_path,
            )
            logger.info(f"[NormStats] Computed and saved to {args.norm_stats_path}: {norm_stats}")
        accelerator.wait_for_everyone()
        norm_stats = load_norm_stats(args.norm_stats_path)

    # ---- 训练集：优先使用 mmap 模式（内存占用极低），否则回退到 LRU 缓存模式 ----
    if args.train_mmap_index is not None:
        train_dataset = MmapSSTDataset(args.train_mmap_index)
        logger.info(f"[Train] Using MmapSSTDataset: {args.train_mmap_index} "
                    f"({len(train_dataset)} patches, physical RAM ≈ 0)")
    else:
        train_dataset = SSTDataset(
            data_root=args.data_root,
            years=args.train_years,
            norm_params=norm_stats,
        )
        logger.info(f"[Train] Using SSTDataset (LRU cache mode): {len(train_dataset)} patches")
    # ---- 验证集：优先使用预抽取的固定验证集，避免占用 LRU cache ----
    if args.val_pt_path is not None:
        val_dataset = FixedValDataset(args.val_pt_path)
        logger.info(f"[Val] Using fixed val set: {args.val_pt_path} ({len(val_dataset)} patches)")
    else:
        val_dataset = SSTDataset(
            data_root=args.data_root,
            years=args.val_years,
            norm_params=norm_stats,
            months=args.val_months,
        )
        logger.info(f"[Val] Using SSTDataset: {len(val_dataset)} patches "
                    f"(consider running prepare_val_set.py for better memory efficiency)")

    # ---- 可选：截取子集（smoke test 用，val_pt_path 模式下通常不需要）----
    if args.max_train_samples is not None:
        n = min(args.max_train_samples, len(train_dataset))
        train_dataset = torch.utils.data.Subset(train_dataset, list(range(n)))
        logger.info(f"[Subset] Training set truncated to {n} patches")

    if args.max_val_samples is not None and args.val_pt_path is None:
        n = min(args.max_val_samples, len(val_dataset))
        indices = random.sample(range(len(val_dataset)), n)
        val_dataset = torch.utils.data.Subset(val_dataset, indices)
        logger.info(f"[Subset] Validation set randomly sampled to {n} patches")

    train_dataloader = DataLoader(
        train_dataset,
        batch_size=args.train_batch_size,
        shuffle=True,
        num_workers=args.dataloader_num_workers,
        pin_memory=True,
        drop_last=True,
        persistent_workers=args.dataloader_num_workers > 0,
    )
    val_dataloader = DataLoader(
        val_dataset,
        batch_size=args.train_batch_size,
        shuffle=False,
        num_workers=args.dataloader_num_workers,
        drop_last=False,
        persistent_workers=args.dataloader_num_workers > 0,
    )

    # ---- 模型构建 ----
    sst_model = build_sst_unet(
        sample_size=args.resolution,
        geo_emb_dim=args.geo_emb_dim,
        block_out_channels=tuple(args.block_out_channels),
        layers_per_block=args.layers_per_block,
        num_train_timesteps=args.ddpm_num_steps,
    )

    geo_embedding = GeoTemporalEmbedding(
        num_fourier_features=args.geo_fourier_features,
        sigma=args.geo_sigma,
    )

    # ---- 噪声调度器 ----
    noise_scheduler = LocalDDPMScheduler(
        num_train_timesteps=args.ddpm_num_steps,
        num_mask_timesteps=args.ddpm_mask_num_steps,
        variance_type="learned_range" if args.prediction_type == "epsilon" else "fixed_small",
    )
    noise_scheduler.register_to_config(prediction_type=args.prediction_type)

    # ---- EMA ----
    if args.use_ema:
        ema_model = EMAModel(
            sst_model.parameters(),
            decay=args.ema_max_decay,
            use_ema_warmup=True,
            inv_gamma=args.ema_inv_gamma,
            power=args.ema_power,
        )

    if args.gradient_checkpointing:
        sst_model.enable_gradient_checkpointing()

    if args.enable_xformers_memory_efficient_attention:
        sst_model.enable_xformers_memory_efficient_attention()

    # ---- 优化器 ----
    optimizer = torch.optim.AdamW(
        list(sst_model.parameters()) + list(geo_embedding.parameters()),
        lr=args.learning_rate,
        betas=(args.adam_beta1, args.adam_beta2),
        weight_decay=args.adam_weight_decay,
        eps=args.adam_epsilon,
    )

    # ---- 计算总训练步数 ----
    num_update_steps_per_epoch = math.ceil(
        len(train_dataloader) / args.gradient_accumulation_steps
    )
    if args.max_train_steps is None:
        args.max_train_steps = args.num_train_epochs * num_update_steps_per_epoch
    args.num_train_epochs = math.ceil(
        args.max_train_steps / num_update_steps_per_epoch
    )

    # ---- 学习率调度器 ----
    lr_scheduler = get_scheduler(
        args.lr_scheduler,
        optimizer=optimizer,
        num_warmup_steps=args.lr_warmup_steps * args.gradient_accumulation_steps,
        num_training_steps=args.max_train_steps * args.gradient_accumulation_steps,
    )

    # ---- 课程学习调度器 ----
    curriculum = MaskCurriculumScheduler(
        total_steps=args.max_train_steps,
        warmup_ratio=args.curriculum_warmup_ratio,
        anneal_ratio=args.curriculum_anneal_ratio,
        min_rate=args.mask_min_rate,
        max_rate=args.mask_max_rate,
        high_freq_sig=args.perlin_high_sig,
        low_freq_sig=args.perlin_low_sig,
    )

    # ---- Accelerator prepare ----
    sst_model, geo_embedding, optimizer, train_dataloader, val_dataloader, lr_scheduler = \
        accelerator.prepare(
            sst_model, geo_embedding, optimizer,
            train_dataloader, val_dataloader, lr_scheduler
        )

    if args.use_ema:
        ema_model.to(accelerator.device)

    weight_dtype = torch.float32
    if accelerator.mixed_precision == "fp16":
        weight_dtype = torch.float16
    elif accelerator.mixed_precision == "bf16":
        weight_dtype = torch.bfloat16

    # ---- 断点续训 ----
    # 注意：必须在 init_trackers 之前完成，使得 global_step 已知，
    # TensorBoard 写入的 step 从正确的值开始，续训时日志不断档。
    global_step  = 0
    first_epoch  = 0
    resume_step  = 0

    if args.resume_from_checkpoint:
        if args.resume_from_checkpoint != "latest":
            resume_path = args.resume_from_checkpoint
        else:
            dirs = [d for d in os.listdir(args.output_dir) if d.startswith("checkpoint")]
            dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
            if dirs:
                resume_path = os.path.join(args.output_dir, dirs[-1])
            else:
                resume_path = None
                logger.warning(
                    f"--resume_from_checkpoint=latest specified but no checkpoint found "
                    f"in {args.output_dir}. Training from scratch."
                )

        if resume_path and os.path.exists(resume_path):
            logger.info(f"Resuming from checkpoint: {resume_path}")
            accelerator.load_state(resume_path)
            global_step = int(resume_path.split("-")[-1])
            first_epoch = global_step // num_update_steps_per_epoch
            resume_step = global_step % num_update_steps_per_epoch

    # ---- 日志初始化（在 resume 之后，global_step 已正确设置）----
    # 续训时使用带 global_step 后缀的 run_name，避免新 event 文件与旧文件
    # 写入同一目录造成步数冲突。TensorBoard --logdir 指向 logs/ 根目录时
    # 会自动合并所有子目录，步数连续即可无缝拼接显示。
    if accelerator.is_main_process:
        os.makedirs(logging_dir, exist_ok=True)
        # TensorBoard 的 add_hparams 不支持 list 类型，需将 list 转为 str
        tb_config = {
            k: str(v) if isinstance(v, list) else v
            for k, v in vars(args).items()
        }
        run_name = ("sst_rad_training" if global_step == 0
                    else f"sst_rad_training_resume{global_step}")
        accelerator.init_trackers(run_name, config=tb_config)

    logger.info("***** Running training *****")
    logger.info(f"  Num examples = {len(train_dataset)}")
    logger.info(f"  Num val examples = {len(val_dataset)}")
    logger.info(f"  Num epochs = {args.num_train_epochs}")
    logger.info(f"  Batch size = {args.train_batch_size}")
    logger.info(f"  Mixed precision = {args.mixed_precision}")
    logger.info(f"  Total optimization steps = {args.max_train_steps}")
    logger.info(f"  Steps per epoch = {num_update_steps_per_epoch}")
    logger.info(f"  Curriculum: warmup={curriculum.warmup_end} steps, "
                f"anneal_end={curriculum.anneal_end} steps")
    logger.info(f"  Checkpointing every {args.checkpointing_steps} steps, "
                f"keep last {args.checkpoints_total_limit}")

    # ============================================================
    # 训练循环
    # ============================================================

    for epoch in range(first_epoch, args.num_train_epochs):
        sst_model.train()
        geo_embedding.train()
        train_loss = 0.0

        progress_bar = tqdm(
            total=num_update_steps_per_epoch,
            disable=not accelerator.is_local_main_process,
            desc=f"Epoch {epoch}",
        )

        for step, batch in enumerate(train_dataloader):
            # 断点续训时跳过已完成的step
            if epoch == first_epoch and step < resume_step:
                if step % args.gradient_accumulation_steps == 0:
                    progress_bar.update(1)
                continue

            # ---- 读取数据 ----
            sst          = batch["sst"].to(dtype=weight_dtype)           # [B, 1, H, W]
            era5         = batch["era5"].to(dtype=weight_dtype)          # [B, 1, H, W]
            land_mask    = batch["land_mask"].to(dtype=weight_dtype)     # [B, 1, H, W]
            static_valid = batch["static_valid"].to(dtype=weight_dtype)  # [B, 1, H, W]
            center_lat   = batch["center_lat"]                           # [B]
            center_lon   = batch["center_lon"]                           # [B]
            day_of_year  = batch["day_of_year"]                          # [B]

            B, _, H, W = sst.shape

            # ---- 课程调度：生成当前step的Perlin掩膜 ----
            # generate_perlin_noise_2d(noise_gen_sst) 在 for 循环外完成 sig/k 计算，
            # rand=True 时内部随机二值化，直接返回 [B, 1, H, W] 的 0/1 掩膜（1=缺失）
            missing_rate, perlin_sig = curriculum.get_params(global_step)
            perlin_sig_int = int(round(perlin_sig))
            perlin_mask = generate_perlin_noise_2d(
                (B, H, W), rand=True, sig=perlin_sig_int
            ).to(sst.device)  # [B, 1, H, W]

            # ---- ERA5 Dropout（Classifier-Free Guidance style）----
            if random.random() < args.era5_dropout_prob:
                era5_input = torch.zeros_like(era5)
            else:
                era5_input = era5

            # ---- 构建3通道输入 ----
            model_input_clean = torch.cat([sst, era5_input, land_mask], dim=1)  # [B, 3, H, W]

            # ---- 加噪（RAD前向过程）----
            noise = torch.randn_like(sst)
            if args.noise_offset:
                noise += args.noise_offset * torch.randn(
                    (B, 1, 1, 1), device=sst.device
                )

            # 采样全局时间步（每个样本一个标量，用于SNR权重计算）
            timestep = torch.randint(
                0, noise_scheduler.config.num_train_timesteps,
                (B,), device=sst.device
            ).long()

            # 设置RAD随机步长
            random_steps, m_steps, om_steps = set_random_steps(args)
            noise_scheduler.random_steps = random_steps
            noise_scheduler.m_steps = m_steps
            noise_scheduler.om_steps = om_steps

            # RAD核心：set_variables用Perlin掩膜设置逐像素噪声水平
            # perlin_mask: [B, 1, H, W]，1=缺失区域（高噪声），0=已知区域（低噪声）
            noise_scheduler.set_variables(perlin_mask, timestep)
            noise_scheduler.mask_idx = noise_scheduler.b_t.nonzero(as_tuple=True)

            # 只对SST通道加噪
            noisy_sst = noise_scheduler.add_noise(sst, noise, timestep)  # [B, 1, H, W]

            # 拼接为3通道（ERA5和LandMask通道不加噪，保持clean）
            noisy_input = torch.cat([noisy_sst, era5_input, land_mask], dim=1)  # [B, 3, H, W]

            # ---- RAD逐像素时间步映射（与原train_RAD.py一致）----
            beta_bar = 1 - noise_scheduler.alphas_cumprod
            beta_bar = torch.hstack(
                (torch.tensor([0.0]), beta_bar[:noise_scheduler.mask_steps])
            ).to(sst.device)

            dist = torch.abs(
                noise_scheduler.b_t_bar.view(-1, 1) - beta_bar[None, :]
            )
            idx_low = torch.argmin(dist, axis=1)
            idx_high = torch.where(idx_low == 0, torch.ones_like(idx_low), idx_low)
            idx_low  = torch.where(
                idx_low == len(beta_bar) - 1, idx_low - 1, idx_low
            )
            idx_high = torch.where(
                (idx_low > 0) & (idx_low < len(beta_bar) - 1) &
                (beta_bar[idx_low] > noise_scheduler.b_t_bar.view(-1)),
                idx_low, idx_high
            )
            idx_low  = torch.where(
                (idx_low > 0) & (idx_low < len(beta_bar) - 1) &
                (beta_bar[idx_low] > noise_scheduler.b_t_bar.view(-1)),
                idx_high - 1, idx_low
            )
            idx_high = torch.where(
                (idx_low > 0) & (idx_low < len(beta_bar) - 1) &
                (beta_bar[idx_low] < noise_scheduler.b_t_bar.view(-1)),
                idx_low + 1, idx_high
            )
            low_val  = torch.take(beta_bar, idx_low)
            high_val = torch.take(beta_bar, idx_high)
            interpolation_factor = (
                noise_scheduler.b_t_bar.view(-1) - low_val
            ) / (high_val - low_val + 1e-8)
            interpolation_factor[high_val == low_val] = 0
            # 逐像素时间步 [B*H*W]，reshape为 [B, 1, H, W]
            timesteps_pixelwise = (
                idx_low + interpolation_factor
            ).view(B, 1, H, W)

            # ---- 地理时空嵌入 ----
            geo_emb = geo_embedding(center_lat, center_lon, day_of_year)  # [B, geo_emb_dim]

            # ---- v-prediction target（仅针对SST通道）----
            if noise_scheduler.config.prediction_type == "v_prediction":
                target = noise_scheduler.get_velocity(sst, noise, timestep)  # [B, 1, H, W]
            elif noise_scheduler.config.prediction_type == "epsilon":
                target = noise  # [B, 1, H, W]
            else:
                raise ValueError(f"Unknown prediction_type: {noise_scheduler.config.prediction_type}")

            # ---- 前向传播 ----
            with accelerator.accumulate(sst_model):
                # 模型输出 [B, 1, H, W]
                model_output = sst_model(
                    noisy_input,
                    timesteps_pixelwise,
                    geo_emb=geo_emb,
                    return_dict=False,
                )[0]

                # ==================================================
                # Loss计算：仅在 Perlin缺失区 ∩ 海洋 ∩ QL=5 的像素上
                # ==================================================

                # loss_mask: 1=计算loss的有效像素，0=忽略
                # perlin_mask: 1=缺失区域（我们要学习重建的地方）
                # static_valid: 1=QL5海洋像素（有可信GT的地方）
                # 两者的交集才是"有可信GT且被我们遮挡了的区域"→ 这是唯一可监督的区域
                loss_mask = perlin_mask * static_valid  # [B, 1, H, W]

                # 逐像素MSE（无reduction）
                raw_loss = F.mse_loss(
                    model_output.float(), target.float(), reduction="none"
                )  # [B, 1, H, W]

                # 应用空间掩膜
                masked_loss = raw_loss * loss_mask

                # Min-SNR权重（v_prediction）
                if args.snr_gamma is not None:
                    # 使用全局标量timestep计算SNR权重
                    snr = compute_snr(noise_scheduler, timestep)  # [B]
                    snr_weights = torch.stack(
                        [snr, args.snr_gamma * torch.ones_like(snr)], dim=1
                    ).min(dim=1)[0]  # [B]

                    if noise_scheduler.config.prediction_type == "epsilon":
                        snr_weights = snr_weights / snr
                    elif noise_scheduler.config.prediction_type == "v_prediction":
                        snr_weights = snr_weights / (snr + 1)

                    # [B] → [B, 1, 1, 1] 广播
                    snr_weights = snr_weights.view(B, 1, 1, 1)
                    masked_loss = masked_loss * snr_weights

                # 在有效像素上求平均（防止除以0）
                valid_count = loss_mask.sum(dim=[1, 2, 3]).clamp(min=1.0)  # [B]
                loss = masked_loss.sum(dim=[1, 2, 3]) / valid_count         # [B]
                loss = loss.mean()                                           # scalar

                # 反向传播
                accelerator.backward(loss)
                if accelerator.sync_gradients:
                    accelerator.clip_grad_norm_(
                        list(sst_model.parameters()) + list(geo_embedding.parameters()),
                        args.max_grad_norm,
                    )
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()

            # ---- 日志与进度 ----
            if accelerator.sync_gradients:
                if args.use_ema:
                    ema_model.step(sst_model.parameters())
                progress_bar.update(1)
                global_step += 1
                train_loss += loss.detach().item()

                # 打印日志
                if global_step % args.log_every_n_steps == 0:
                    avg_loss = train_loss / max(global_step, 1)
                    lr_now   = lr_scheduler.get_last_lr()[0]

                    # 课程阶段标签
                    if global_step < curriculum.warmup_end:
                        stage = "warmup"
                    elif global_step < curriculum.anneal_end:
                        stage = "anneal"
                    else:
                        stage = "stable"

                    # 诊断指标
                    loss_mask_ratio = loss_mask.mean().item()           # 有效像素比例
                    out_mean  = model_output.float().mean().item()
                    out_std   = model_output.float().std().item()
                    has_nan   = model_output.isnan().any().item()
                    noisy_std = noisy_sst.float().std().item()

                    accelerator.log({
                        "train_loss":        loss.detach().item(),
                        "avg_train_loss":    avg_loss,
                        "learning_rate":     lr_now,
                        "missing_rate":      missing_rate,
                        "perlin_sig":        perlin_sig,
                        "loss_mask_ratio":   loss_mask_ratio,
                        "output_mean":       out_mean,
                        "output_std":        out_std,
                        "noisy_sst_std":     noisy_std,
                        "epoch":             epoch,
                        "curriculum_stage":  stage,
                    }, step=global_step)

                    if accelerator.is_main_process:
                        logger.info(
                            f"[{stage}] Step {global_step}/{args.max_train_steps} "
                            f"Epoch {epoch} | "
                            f"loss={loss.detach().item():.4f} avg={avg_loss:.4f} | "
                            f"lr={lr_now:.2e} | "
                            f"mask_rate={missing_rate:.2f} sig={perlin_sig:.1f} | "
                            f"valid_px={loss_mask_ratio:.2%} | "
                            f"out μ={out_mean:.3f} σ={out_std:.3f}"
                            + (" ⚠ NaN!" if has_nan else "")
                        )

                # 保存检查点 + 验证（每 val_every_n_steps 步触发，与 checkpointing 对齐）
                if global_step % args.checkpointing_steps == 0:
                    if accelerator.is_main_process:
                        # 清理旧检查点
                        if args.checkpoints_total_limit is not None:
                            ckpts = sorted(
                                [d for d in os.listdir(args.output_dir) if d.startswith("checkpoint")],
                                key=lambda x: int(x.split("-")[-1])
                            )
                            if len(ckpts) >= args.checkpoints_total_limit:
                                for ckpt in ckpts[:len(ckpts) - args.checkpoints_total_limit + 1]:
                                    shutil.rmtree(os.path.join(args.output_dir, ckpt))

                        save_path = os.path.join(args.output_dir, f"checkpoint-{global_step}")
                        accelerator.save_state(save_path)
                        logger.info(f"Checkpoint saved to {save_path}")

                # 按 step 触发验证，不依赖 epoch 边界，续训时也不会漏验证
                if global_step % args.val_every_n_steps == 0:
                    if accelerator.is_main_process:
                        _run_validation(
                            sst_model, geo_embedding, noise_scheduler,
                            val_dataloader, accelerator, weight_dtype,
                            args, global_step, epoch, norm_stats,
                        )

                if global_step >= args.max_train_steps:
                    break

        progress_bar.close()
        if global_step >= args.max_train_steps:
            break

    # ---- 保存最终模型 ----
    accelerator.wait_for_everyone()
    if accelerator.is_main_process:
        unet_unwrapped = accelerator.unwrap_model(sst_model)
        geo_unwrapped  = accelerator.unwrap_model(geo_embedding)

        if args.use_ema:
            ema_model.copy_to(unet_unwrapped.parameters())

        torch.save(unet_unwrapped.state_dict(),
                   os.path.join(args.output_dir, "sst_rad_unet_final.pt"))
        torch.save(geo_unwrapped.state_dict(),
                   os.path.join(args.output_dir, "sst_rad_geo_emb_final.pt"))
        logger.info("Final model saved.")

    accelerator.end_training()


# ============================================================
# 验证函数
# ============================================================

@torch.no_grad()
def _run_validation(
    model, geo_embedding, noise_scheduler,
    val_dataloader, accelerator, weight_dtype,
    args, global_step, epoch, norm_stats,
):
    """
    在验证集上计算:
      - 全图 RMSE（QL5海洋区域）
      - 仅补全区 RMSE（Perlin缺失区 ∩ QL5海洋）
    推理方式：DDIM，ddpm_num_inference_steps 步。
    可视化：每次验证保存 vis_num_samples 张对比图。
    """
    model.eval()
    geo_embedding.eval()

    # 构建 DDIM 调度器（与训练调度器配置一致）
    ddim_scheduler = LocalDDIMScheduler(
        num_train_timesteps=args.ddpm_num_steps,
        num_mask_timesteps=args.ddpm_mask_num_steps,
        prediction_type=args.prediction_type,
    )
    ddim_scheduler.set_timesteps(args.ddpm_num_inference_steps)

    all_rmse_global  = []
    all_rmse_inpaint = []
    vis_saved        = False   # 只保存第一个batch的可视化

    val_perlin_sig = 5   # 验证时固定中等频率

    t_min   = norm_stats["t_min"]
    t_scale = norm_stats["t_max"] - norm_stats["t_min"]

    for batch_idx, batch in enumerate(val_dataloader):
        sst          = batch["sst"].to(dtype=weight_dtype, device=accelerator.device)
        era5         = batch["era5"].to(dtype=weight_dtype, device=accelerator.device)
        land_mask    = batch["land_mask"].to(dtype=weight_dtype, device=accelerator.device)
        static_valid = batch["static_valid"].to(dtype=weight_dtype, device=accelerator.device)
        center_lat   = batch["center_lat"].to(accelerator.device)
        center_lon   = batch["center_lon"].to(accelerator.device)
        day_of_year  = batch["day_of_year"].to(accelerator.device)

        B, _, H, W = sst.shape

        perlin_mask = generate_perlin_noise_2d(
            (B, H, W), rand=True, sig=val_perlin_sig
        ).to(sst.device)  # [B, 1, H, W]

        geo_emb = geo_embedding(center_lat, center_lon, day_of_year)

        # ---- DDIM 去噪推理 ----
        # 从纯噪声出发，仅对缺失区域去噪（已知区域用 clean SST 覆盖）
        noisy_sst = torch.randn_like(sst)

        random_steps, m_steps, om_steps = set_random_steps(args)
        ddim_scheduler.random_steps = random_steps
        ddim_scheduler.m_steps      = m_steps
        ddim_scheduler.om_steps     = om_steps

        # 用最大时间步初始化 set_variables（推理阶段用固定全噪声时间步）
        init_timestep = torch.full((B,), args.ddpm_num_steps - 1,
                                   dtype=torch.long, device=sst.device)
        ddim_scheduler.set_variables(perlin_mask, init_timestep)
        ddim_scheduler.mask_idx = ddim_scheduler.b_t.nonzero(as_tuple=True)

        for i, t in enumerate(ddim_scheduler.timesteps):
            t_batch = torch.full((B,), t, dtype=torch.long, device=sst.device)

            # 已知区域用 clean SST，缺失区域保留当前噪声状态
            noisy_input = noisy_sst * perlin_mask + sst * (1 - perlin_mask)
            noisy_input = torch.cat([noisy_input, era5, land_mask], dim=1)

            # 逐像素时间步映射
            beta_bar = 1 - ddim_scheduler.alphas_cumprod
            beta_bar = torch.hstack(
                (torch.tensor([0.0]), beta_bar[:ddim_scheduler.mask_steps])
            ).to(sst.device)
            dist    = torch.abs(ddim_scheduler.b_t_bar.view(-1, 1) - beta_bar[None, :])
            idx_low = torch.argmin(dist, axis=1)
            timesteps_pix = idx_low.float().view(B, 1, H, W)

            model_output = model(noisy_input, timesteps_pix,
                                 geo_emb=geo_emb, return_dict=False)[0]

            # ---- 手动执行 DDIM update，绕过 step() 内部的 set_variables ----
            # 避免 step() 内部用标量/0-dim prev_t 调用 set_variables 导致的
            # 形状不匹配和设备不一致问题。

            # 计算 prev_t_batch（[B] 形状）
            if i + 1 < len(ddim_scheduler.timesteps):
                prev_t_val = ddim_scheduler.timesteps[i + 1].item()
            else:
                prev_t_val = -1
            prev_t_batch = torch.full((B,), prev_t_val, dtype=torch.long, device=sst.device)

            # 当前时间步的 alpha
            ddim_scheduler.set_variables(perlin_mask, t_batch)
            alpha_prod_t = ddim_scheduler.a_t_bar.clone()

            # 前一时间步的 alpha
            if prev_t_val < 0:
                alpha_prod_t_prev = torch.ones_like(alpha_prod_t)
            elif t.item() >= ddim_scheduler.mask_steps and prev_t_val < ddim_scheduler.mask_steps:
                alpha_prod_t_prev = 1 - ddim_scheduler.nu * perlin_mask
            else:
                ddim_scheduler.set_variables(perlin_mask, prev_t_batch)
                alpha_prod_t_prev = ddim_scheduler.a_t_bar.clone()
                ddim_scheduler.set_variables(perlin_mask, t_batch)  # 恢复当前步

            beta_prod_t      = 1 - alpha_prod_t
            beta_prod_t_prev = 1 - alpha_prod_t_prev
            current_alpha_t  = alpha_prod_t / alpha_prod_t_prev.clamp(min=1e-20)
            current_beta_t   = 1 - current_alpha_t

            # 预测类型解码
            if ddim_scheduler.config.prediction_type == "v_prediction":
                pred_original_sample = (alpha_prod_t**0.5) * noisy_sst - (beta_prod_t**0.5) * model_output
                pred_epsilon         = (alpha_prod_t**0.5) * model_output + (beta_prod_t**0.5) * noisy_sst
            elif ddim_scheduler.config.prediction_type == "epsilon":
                pred_original_sample = (noisy_sst - beta_prod_t**0.5 * model_output) / alpha_prod_t**0.5
                pred_epsilon         = model_output
            else:
                raise ValueError(f"Unknown prediction_type: {ddim_scheduler.config.prediction_type}")

            # clip predicted x_0
            if ddim_scheduler.config.clip_sample:
                pred_original_sample = pred_original_sample.clamp(
                    -ddim_scheduler.config.clip_sample_range,
                    ddim_scheduler.config.clip_sample_range,
                )

            # DDIM update（eta=0，确定性采样）
            pred_sample_direction = beta_prod_t_prev.clamp(min=0) ** 0.5 * pred_epsilon
            prev_sample = alpha_prod_t_prev**0.5 * pred_original_sample + pred_sample_direction
            noisy_sst = torch.where(current_beta_t == 0, noisy_sst, prev_sample)

        pred = noisy_sst  # 去噪完成后即为重建结果

        # ---- RMSE 计算（反归一化到 Kelvin）----
        pred_k = (pred.float() + 1.0) / 2.0 * t_scale + t_min
        sst_k  = (sst.float()  + 1.0) / 2.0 * t_scale + t_min

        valid      = static_valid.float()
        diff2      = ((pred_k - sst_k) ** 2) * valid
        rmse_global = torch.sqrt(diff2.sum() / valid.sum().clamp(min=1))

        inpaint_valid = perlin_mask * static_valid
        diff2_inp     = ((pred_k - sst_k) ** 2) * inpaint_valid
        rmse_inpaint  = torch.sqrt(diff2_inp.sum() / inpaint_valid.sum().clamp(min=1))

        all_rmse_global.append(rmse_global.item())
        all_rmse_inpaint.append(rmse_inpaint.item())

        # ---- 可视化（只取第一个batch的前N个样本）----
        if not vis_saved:
            _save_vis(
                sst=sst, era5=era5, land_mask=land_mask,
                perlin_mask=perlin_mask, pred=pred,
                t_min=t_min, t_scale=t_scale,
                n=min(args.vis_num_samples, B),
                save_dir=os.path.join(args.output_dir, "vis"),
                epoch=epoch, global_step=global_step,
            )
            vis_saved = True

    # ---- 汇总指标 ----
    mean_rmse_global  = float(np.mean(all_rmse_global))
    mean_rmse_inpaint = float(np.mean(all_rmse_inpaint))
    std_rmse_global   = float(np.std(all_rmse_global))
    std_rmse_inpaint  = float(np.std(all_rmse_inpaint))

    accelerator.log({
        "val_rmse_global":      mean_rmse_global,
        "val_rmse_inpaint":     mean_rmse_inpaint,
        "val_rmse_global_std":  std_rmse_global,
        "val_rmse_inpaint_std": std_rmse_inpaint,
    }, step=global_step)

    logger.info(
        f"[Validation] Epoch {epoch} Step {global_step} | "
        f"RMSE(global)={mean_rmse_global:.4f}±{std_rmse_global:.4f} K | "
        f"RMSE(inpaint)={mean_rmse_inpaint:.4f}±{std_rmse_inpaint:.4f} K"
    )

    model.train()
    geo_embedding.train()


# ============================================================
# 可视化辅助函数
# ============================================================

def _save_vis(sst, era5, land_mask, perlin_mask, pred,
              t_min, t_scale, n, save_dir, epoch, global_step):
    """
    保存对比图：原始SST | Perlin掩膜 | noisy输入（掩膜后） | 重建SST | 误差图
    每个样本一行，共 n 行，保存为单张 PNG。
    """
    os.makedirs(save_dir, exist_ok=True)

    # 反归一化到 Kelvin，转为 CPU numpy
    def to_kelvin(t):
        return ((t.float() + 1.0) / 2.0 * t_scale + t_min).cpu().numpy()

    sst_k  = to_kelvin(sst[:n, 0])    # [n, H, W]
    pred_k = to_kelvin(pred[:n, 0])   # [n, H, W]
    mask_np   = perlin_mask[:n, 0].float().cpu().numpy()   # [n, H, W]  1=缺失
    land_np   = land_mask[:n, 0].float().cpu().numpy()     # [n, H, W]  1=陆地

    # noisy 输入：已知区域用 clean SST，缺失区域置为 NaN 以显示灰色
    noisy_k = sst_k.copy()
    noisy_k[mask_np > 0.5] = np.nan

    ncols = 5
    fig, axes = plt.subplots(n, ncols, figsize=(ncols * 4, n * 3.5),
                              constrained_layout=True)
    if n == 1:
        axes = axes[np.newaxis, :]

    col_titles = ["GT SST (K)", "Perlin Mask\n(white=missing)",
                  "Input (masked)", "Pred SST (K)", "Error |ΔK|"]

    vmin = float(np.nanpercentile(sst_k, 2))
    vmax = float(np.nanpercentile(sst_k, 98))

    for i in range(n):
        err = np.abs(pred_k[i] - sst_k[i])
        err[land_np[i] > 0.5] = np.nan   # 陆地不显示误差

        imgs   = [sst_k[i], mask_np[i], noisy_k[i], pred_k[i], err]
        cmaps  = ["RdYlBu_r", "gray", "RdYlBu_r", "RdYlBu_r", "hot_r"]
        vmins  = [vmin, 0, vmin, vmin, 0]
        vmaxs  = [vmax, 1, vmax, vmax, float(np.nanpercentile(err, 95) + 1e-3)]

        for j, (img, cmap, v0, v1, title) in enumerate(
                zip(imgs, cmaps, vmins, vmaxs, col_titles)):
            ax = axes[i, j]
            im = ax.imshow(img, cmap=cmap, vmin=v0, vmax=v1, origin="upper")
            plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            if i == 0:
                ax.set_title(title, fontsize=9)
            ax.axis("off")

    fig.suptitle(f"Epoch {epoch}  Step {global_step}", fontsize=11)
    save_path = os.path.join(save_dir, f"epoch{epoch:04d}_step{global_step:07d}.png")
    fig.savefig(save_path, dpi=100)
    plt.close(fig)
    logger.info(f"[Vis] Saved to {save_path}")
if __name__ == '__main__':
    main()